[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0xbcbcbc"
blue = "0xd75f00"
cyan = "0x005faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0x444444"
text = "0xeeeeee"

[colors.normal]
black = "0xeeeeee"
blue = "0x0087af"
cyan = "0x005f87"
green = "0x008700"
magenta = "0x878787"
red = "0xaf0000"
white = "0x444444"
yellow = "0x5f8700"

[colors.primary]
background = "0xeeeeee"
foreground = "0x444444"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 50000

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 90
lines = 22

[window.padding]
x = 5
y = 5
